syntax = "proto3";

package spot;

option go_package = "github.com/Samurosa/exchange-contract/protobuf/gen/go/spot;spot";

import "google/protobuf/timestamp.proto";
import "google/protobuf/empty.proto";
import "validate/validate.proto";
import "user/user.proto";


service SpotInstrumentService {

    rpc CreateSpot(CreateSpotRequest)
        returns (CreateSpotResponse);
        
    rpc GetSpot(GetSpotRequest)
        returns (GetSpotResponse);

    rpc EnableSpot(EnableSpotRequest)
        returns (google.protobuf.Empty);

    rpc DisableSpot(DisableSpotRequest)
        returns (google.protobuf.Empty);

    rpc ListSpots (SpotListRequest)
        returns (SpotListResponse);
}

enum SpotStatus {
    SPOT_STATUS_UNSPECIFIED = 0;
    SPOT_STATUS_ACTIVE = 1;
    SPOT_STATUS_DISABLED = 2;
}

message SpotListItem {
    string id = 1;

    string base_asset = 2;
    string quote_asset = 3;

    string name = 4;
    string description = 5;

    SpotStatus status = 6;

    google.protobuf.Timestamp created_at = 7;
}

message CreateSpotRequest {
    string base_asset  = 1 [
        (validate.rules).string = {
            min_len: 2,
            max_len: 10,
            pattern: "^[A-Z]+$"
        }
    ];

    string quote_asset = 2 [
        (validate.rules).string = {
            min_len: 2,
            max_len: 10,
            pattern: "^[A-Z]+$"
        }
    ];

    int32  price_precision = 3 [
        (validate.rules).int32 = {
            gte: 0,
            lte: 10,
        }
    ];

    int32  quantity_precision = 4 [
            (validate.rules).int32 = {
            gte: 0,
            lte: 10,
        }
    ];

    string min_order_size = 5 [
        (validate.rules).string = {
            min_len: 1,
            pattern: "^[0-9]+(\\.[0-9]+)?$",
        }
    ];

    string max_order_size = 6 [
        (validate.rules).string = {
            min_len: 1,
            pattern: "^[0-9]+(\\.[0-9]+)?$",
        }
    ];

    repeated user.Role allowed_roles = 7 [
        (validate.rules).repeated = {
            min_items: 1,
            unique: true,
        }
    ];

    string name = 8 [
        (validate.rules).string = {
            min_len: 1,
            max_len: 50,
        }
    ];

    string description = 9 [
        (validate.rules).string = {
            max_len: 200,
        }
    ];

}

message CreateSpotResponse {
    string id = 1;

    google.protobuf.Timestamp created_at = 2;
}


message GetSpotRequest{
    string id = 1 [
        (validate.rules).string.uuid = true
    ];
}

message GetSpotResponse{
    string id     = 1; //уникальный идентификатор

    string base_asset  = 2; //актив который продают или покупают
    string quote_asset = 3; //в чем выражается цена

    int32  price_precision    = 4; // количество знаков после запятой у цены
    int32  quantity_precision = 5; // количество знаков после запятой у актива
    string min_order_size     = 6; // минимальное возможное количество покупки/продажи
    string max_order_size     = 7; // максимальное количество покупки актива

    SpotStatus status = 8; // статус спота
    repeated user.Role allowed_roles = 9; //разрешенные роли у пользователей

    string name        = 10; // название спота
    string description = 11; // описание спота

    google.protobuf.Timestamp created_at = 12; // время создания
    google.protobuf.Timestamp updated_at = 13; // время обновления
    google.protobuf.Timestamp disable_at = 14; // время обновления
}

message EnableSpotRequest {
    string id = 1 [
        (validate.rules).string.uuid = true
    ];
}

message DisableSpotRequest {
    string id = 1 [
        (validate.rules).string.uuid = true
    ];
}

message SpotListRequest {
    int32 page_size = 1 [
        (validate.rules).int32 = {
            gte: 1,
            lte: 100
        }
    ];

    optional string cursor = 2;

    optional SpotStatus status = 3;

    optional string base_asset = 4;

    optional string quote_asset = 5;
}

message SpotListResponse {
    repeated SpotListItem spots = 1;

    string next_cursor = 2;

    bool has_more = 3;
}